### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by FrancosLab** [cj/vues#1]
Would be awesome to see some usage/documentation.

Love seeing projects like Next.js and Nuxt.js pop up.

**Comment by cj** [comment]
@FrancosLab I plan to have full documentation in the next few weeks.

**Comment by cj** [comment]
@FrancosLab I haven't forgotten about you :)

I've done a complete rewrite, it's a lot cleaner code base with 100% test coverage now.  The docs will be up by Monday.  Have a great weekend!

**Comment by FrancosLab** [comment]
@cj Awesome, look forward to it!
